# -*- coding: utf-8 -*-
{
 'name': "Comptabilité des marchés",
 'summary': "Gestion des marche",
 'description': "Gestion des listes des marche et la soustraitancee",
 'author': "Saad",
 'sequence': -106,
 'website': "http://www.example.com",
 'category': 'Productivity',
 'version': '0.1',
 'depends': ['base','web_domain_field'],
 'data': ['views/liste_des_marches.xml',
          'views/attachements_reel.xml',
          'views/attachements_mo.xml',
          'views/assets.xml',
          'views/list_des_devis_sst.xml',
          'report/rapport_attachelent_reel.xml',
          'report/report.xml'],
 'demo': [],
 'application': True,
}